export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER'
export const SET_CURRENT_USER_FROM_TOKEN = 'SET_CURRENT_USER_FROM_TOKEN'

export const UNAUTHORIZED = '_UNAUTHORIZED'
export const UNDEFINED = '_UNDEFINED'
export const SUCCESS = '_SUCCESS'