export const FETCH_ALARM_DATA = 'FETCH_ALARM_DATA'
export const ALARM_TYPE_LOAD_ALL = 'ALARM_TYPE_LOAD_ALL'
export const SAVE_FILTERING_AND_ORDERING_DATA = 'SAVE_FILTERING_AND_ORDERING_DATA'
export const RESOLVE_ALARM = 'RESOLVE_ALARM'
export const LOAD_RESOLVED_ALARM = 'LOAD_RESOLVED_ALARM'


export const SUCCESS = '_SUCCESS'
export const UNAUTHORIZED = '_UNAUTHORIZED'
export const FAILURE = '_FAILURE'
